### ISSUE TITLE
OBEPPlugin 

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#1]
Assigned to Dian 
Estimate 12 hrs 
1st plugin 
WI - 23880

https://pay.apps.ok.gov/OSBEP/_app/search/index.php

**Comment by InnocenceD** [comment]
Worked 4 hr from 2pm to 6 pm.

**Comment by InnocenceD** [comment]
worked 4 hrs

**Comment by InnocenceD** [comment]
worked 2 hrs 10/11/2018
finishing up sanction and formatting
