### ISSUE TITLE
WICVPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#10]
estimate 10 hrs 
WI - 24054

https://app.wi.gov/licensesearch

**Comment by InnocenceD** [comment]
worked 1.5 hr for preparation on the updated version of web scraper (trying to run old plugins, add references, updated third-party library) (didnt push any code yet)

**Comment by InnocenceD** [comment]
worked 1.5 hr for setting up WICVPlugIn and finished the searching part

**Comment by InnocenceD** [comment]
worked 3 hrs, finished testing the first search block (search by individual names and/or license number), need clarification on doing other search blcoks.
