### ISSUE TITLE
IDBPPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#11]
estimate 8 hrs 
WI - 2415

https://idbop.mylicense.com/verification/Search.aspx

**Comment by timferido** [comment]
10/17/18 - worked for 12 mins

start: 9:52a
end: 10:04a

- setting up new plugin

**Comment by timferido** [comment]
10/18/18 - worked for 20 mins

start: 3:00p
end: 3:20p

- finished setting up plugin

**Comment by timferido** [comment]
10/20/18 - worked for 1 hr

- pushed up changes
- changed base url
- found test cases
- replicating http request

**Comment by timferido** [comment]
10/25/18 - worked for 1 hr

- got first request to get cookies and viewstate
- got second request to get to search results page

**Comment by timferido** [comment]
10/26/18 - worked for 1.5 hr

- got 3rd request to open details page
- working on web parse

**Comment by timferido** [comment]
10/27/18  - worked for 1 hr

- working on regex to collect correct info on web parse

**Comment by timferido** [comment]
10/28/18 - worked for 1 hr

- cleaned up web parse
- completed plugin
