### ISSUE TITLE
ABECPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#14]
estimate 8 hrs 
WI 23996
search by lic# and/or last name 
Supports Exp  (no sanctions) 

http://www.abec.state.al.us/licensee.aspx

**Comment by InnocenceD** [comment]
Worked 2 hrs from 9.30 to 11.30 to set up ABECPlugin. Finished the first search part. Running into no-breakpoint issue.

**Comment by InnocenceD** [comment]
Worked 3 hrs from 8:30 to 11:30. Complete the plugin. Await for verification.
