### ISSUE TITLE
ARBECPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#15]
estimate 8 hrs 
WI 23999
Search by lic# and/or last name 
supports expirables and sanctions

http://search.statesolutions.us/?A=ABEC&AID=RS

**Comment by timferido** [comment]
11/05/18 - worked for 1 hour

- set up plugin
- moved IDBP to completed
- found test cases
- running into error setting up plugin

**Comment by timferido** [comment]
11/07/18 - worked for 1 hour

- writing document for setting up new plugins

**Comment by timferido** [comment]
11/13/18 - worked for 1 hour

- got plugin to run
- looking for test cases
- got to results page
- got to details page

**Comment by timferido** [comment]
11/14/18 - worked for 1 hour

- working on webparse
- got details

**Comment by timferido** [comment]
11/14/18 - worked for 1 hour

- still working on webparse

**Comment by timferido** [comment]
11/15/18 - worked for 2 hours

- got all details to display correctly
- web parse complete
- checking sanctions
- adding more test cases
- finished plugin
