### ISSUE TITLE
CDRAPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#16]
estimate 8 hrs 
WI 24001
search by lic# or  first + last 
supports expirables and sanctions

https://apps.colorado.gov/dora/licensing/Lookup/LicenseLookup.aspx

**Comment by M3L6H** [comment]
10/31/2018 - Initial setup. Started search. (1 hr 30 mins - 10:05AM-11:35AM)

**Comment by M3L6H** [comment]
11/09/2018 - Plugin complete. Awaiting verification. (4 hrs - 4:25PM-8:25PM)
