### ISSUE TITLE
MBBHTPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#17]
estimate 8 hrs 
WI 24018 
search by lic# or   first + last
supports expirables and sanctions 

https://bht.hlb.state.mn.us/DesktopModules/ServiceForm.aspx?svid=37&mid=178

**Comment by M3L6H** [comment]
Finished setup. Working on search. (1hr 40 min - 7:50AM-8:30AM)

**Comment by M3L6H** [comment]
Recovered from data loss. Finished search. (2 hrs - 6:00PM-8:00PM)

**Comment by M3L6H** [comment]
Finished plugin. Awaiting verification. (2hrs 30min - 9:00AM-11:30AM)
