### ISSUE TITLE
NVADGPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#19]
estimate 8 hrs
WI 24025
search by lic# and/or full name
supports expirables and sanctions 

https://nvadg.glsuite.us/GLSuiteWeb/Clients/NVADG/Public/Verification/Search.aspx

**Comment by M3L6H** [comment]
10/20/2018 - Plugin complete. Awaiting verification (3hrs 40min - 9:00AM-12:40PM)
