### ISSUE TITLE
IDFPRPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#23]
estimate time 8 hrs 
WI 24009
https://ilesonline.idfpr.illinois.gov/DFPR/Lookup/LicenseLookup.aspx
List and details page are popups
must have a license type search parameter 

Some providers have multiple licenses 
supports Sanctions (ever disciplined ) and Expendables (Expiration date) 

Capture other license details on web_parse but don't base Sanctions and Expendables off them.
Add a td_single (to create a header) to distinguish "other license" details from main details

**Comment by M3L6H** [comment]
12/04/2018 - Plugin complete. Awaiting verification. (2 hrs 20 min - 2:50PM-5:10PM)
