### ISSUE TITLE
AMCBPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#24]
estimate 4 hrs
WI 23802
https://ams.amcbmidwife.org/amcbssa/f?p=AMCBSSA:17800

relatively easy plugin 
supports sanctions and expirables 
no details page 
dont support multiple providers

**Comment by M3L6H** [comment]
12/03/2018 - Plugin complete. Awaiting verification. (1 hr 50 min - 3:20PM-5:10PM)
