### ISSUE TITLE
DCAPlugIn 

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#25]
estimate 10 hrs 
WI 26134
https://search.dca.ca.gov/

details page may be very hard to capture 
supports Expirables (exp date on the side) 
Some providers have a Disciplinary actions field so support Sanctions 
Since the details page can be shorter or longer depending on provider, 
make sure to have some providers with details page with more then just "License Details"

**Comment by M3L6H** [comment]
11/23/2018 - Completed setup. Ran into an issue with site. (1 hr 30 min - 9:30AM-11:00AM)
