### ISSUE TITLE
DPFRPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#26]
estimate 8 hrs 
WI 24205
https://www.pfr.maine.gov/ALMSOnline/ALMSQuery/SearchIndividual.aspx
supports sanctions and expirables 

Plugin already has had some work done
Use DPRFPlugin in the WIP folder as a template 
or you can remake using webParse and webScarper method if that works easier for you. 
Make sure user needs to search by name and license number, return error (from validate) if
one of those fields is empty

provider may have multiple licenses, only grab details regarding match license number

**Comment by timferido** [comment]
11/28/18 - worked for 2 hours

- got regex for detail query
- got to details page

**Comment by timferido** [comment]
11/29/18 - worked for 1 hour

- working on webparse

**Comment by timferido** [comment]
12/14/18 - worked for 1 hour

- worked on webparse
- got all details on page
- working on sanctions, expirations, and isolating desired license number

**Comment by timferido** [comment]
12/17/18 - worked for 2 hours

- successfully isolated desired license details
- successfully detecting sanctions and acquiring provider name
- successfully setting expiration
- completed plugin awaiting verification
