### ISSUE TITLE
VTCVPlugIn 

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#27]
estimate 10 hrs 
WI 24049
https://secure.professionals.vermont.gov/prweb/PRServletCustom/V9csDxL3sXkkjMC_FR2HrA%5B%5B*/!STANDARD?UserIdentifier=LicenseLookupGuestUser

make search by name and/ or license number 

Instead of having to use title as a search parameter and having to write a crazy switch case. Have the query string set all of the title checkbox parameters (ie set parameters to true, will make more sense when you see query) if this doesn't work let me know

Supports Expiration 
Supports Sanction (use case History: no cases == no sanctions)

**Comment by M3L6H** [comment]
11/09/2018 - Initial setup. Finished search. (2 hrs 30 min - 4:33PM-7:03PM)

**Comment by M3L6H** [comment]
11/14/2018 - Plugin complete. Awaiting verification. (3 hrs 30 min - 1:30PM-5:00PM)
