### ISSUE TITLE
KSBNPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#28]
estimate 8 hrs 
WI 25790
https://www.kansas.gov/ksbn-verifications/search/records

plugin searchs only by license number (not name)
error if multiple providers 
Supports Expiration 
Supports Sanction(flag red only if status == revoked)

**Comment by timferido** [comment]
11/20/18 - worked for 2 hours

- setup plugin
- finding test cases
- working on websearch

**Comment by timferido** [comment]
11/20/18 - worked for 1 hour

- forming client and response
- method to retrieve csrftoken and cookies
- got to details page
- finished websearch

**Comment by timferido** [comment]
11/22/18 - worked for 1 hour

- finished webparse
- finished plugin

**Comment by timferido** [comment]
11/26/18 - worked for 1 hour

- edited webparse
- handled sanctions if "Revoked"
- finished plugin
- pushed changes
