### ISSUE TITLE
IDCVPlugin

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#3]
estimated time: 10 hr 
First plugin 
WI - 24008

https://secure.ibol.idaho.gov/eIBOLPublic/LPRBrowser.aspx

**Comment by jiajinliang** [comment]
Worked 4 hours on IDCVPlugIn on 10/06/2018

**Comment by jiajinliang** [comment]
last time studied with Paul and Peter and get started on WebSearch.cs

**Comment by jiajinliang** [comment]
Today 10/12/2018
Worked from 2:00 to 9:00 with Tim and Peter
Finished WebSearch.cs and WebParse.cs
Finished testing
