### ISSUE TITLE
IBPLPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#4]
Estimate 10 hrs 
First plugin
WI - 24011

https://ibplicense.iowa.gov/PublicPortal/Iowa/IBPL/publicsearch/publicsearch.jsp

**Comment by M3L6H** [comment]
10/06/2018 - Setup (3hrs)

**Comment by M3L6H** [comment]
10/07/2018 - Results Page (1hr)

**Comment by M3L6H** [comment]
10/07/2018 - Got to details page (1hr - 10:45AM-11:45AM)

**Comment by M3L6H** [comment]
10/07/2018 - Plugin complete. Moving to testing (1hr - 7:30PM-8:30PM)

**Comment by M3L6H** [comment]
10/08/2018 - Testing complete. Cleaned up code. Awaiting verification (1hr - 10:00AM-11:00AM)
