### ISSUE TITLE
OBLCPlugIn

### ISSUE THREAD

**Issue by Pholbel** [Pholbel/Plugins-yr2#7]
Michael's 2nd plugin 
estimate 10hrs 
WI - 23034

https://hrlb.oregon.gov/oblpct/licenseelookup/index.asp

**Comment by M3L6H** [comment]
10/11/2018 - Got to details page (2hrs - 6:30AM-8:30AM)

**Comment by M3L6H** [comment]
10/11/2018 - Plugin complete. Awaiting verification (1hr - 9:30AM-10:30AM)
